name: upload

on: workflow_dispatch

jobs:
  upload:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: upload
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Commit dist
        run: |
          cd Sweet-Cloud-Dist
          rm -rf dist
          cp -r ../Sweet-Cloud-Web/dist .
          git add .
          git config --local user.email "i@nn.ci"
          git config --local user.name "Noah Hsu"
          git commit --amend -m "upload dev dist"
          cd ..

      - name: Upload dist files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: dev
          directory: Sweet-Cloud-Dist
          repository: long2005a1/Sweet-Cloud-Dist
          force: true
